E27-29-SWE-LocalTours/swe-local-tours-fe

package-lock.json, package.json, postcss.config.js, src/app/tours/page.js, src/components/TourCard.js, src/styles/globals.css, tailwind.config.js
Added tailwind, fontawesome to project.
Created basic tour cards.
#2
=> added tailwind, fontawesome, and tour cards

package-lock.json, src/api/locationData.js, src/api/mergedData.js, src/app/location/new/page.js, src/app/locations/page.js, src/components/LocationCard.js
The following tickets are not completed yet, but were touched on in this PR: #18, #14
- See the location card on locations page
- Unable to test further yet without data
=> location card component, worked on view all locations, api calls for view location details

src/app/layout.js, src/app/tour/new/page.js, src/app/tours/page.js, src/components/TourCard.js, src/components/forms/TourForm.js
- Added skeleton for tour form
- Made slight edit to tour cards so that the words "delete" and "edit" show up when hovering over the icons
- Edited the title of the page visible in the tab of a web browser to Local Tours
- **Still need to add time and date pickers for the time/date input**
#10 
Creates a visual indication for what the new tour form will look like
Once the date/time picker stuff is done, console.log the values of the form data on submit so we know the payload that will be sent to the backend.
=> Barebones tour form

package-lock.json, package.json, src/components/TourCard.js, src/components/forms/TourForm.js
- Added date picker and time picker from material UI (https://mui.com/x/react-date-pickers/)
- Tour form has base functionality, creates payload object and console logs it on submit, then routes to tours page.
#10 
We can pass values into the tour form and they are saved into the payload object on submit.
Form can be submitted with various responses, including blank ones, and it should prompt you to enter something into every field (it does not do that right now)
=> 10 create new tour form

src/app/locations/page.js, src/components/LocationCard.js
- hover styling on location cards edit and delete buttons
- add location button small change
#18
for consistent styling across pages
See locations page and make sure hover text shows up for edit and delete buttons
=> small updates to locations UI to match tours page for style consistency

src/api/locationData.js, src/app/locations/page.js, src/components/LocationCard.js
Tested fetching location data from backend.
=> Frontend backend connection

src/app/location/[id]/page.js, src/components/LocationCard.js
- added info icon for view details on location card component
- added edit and delete on location details page
#18 #19
=> Locations card & Location Details page small UI changes

src/api/locationData.js, src/app/location/edit/[id]/page.js, src/app/locations/page.js, src/components/forms/LocationForm.js
=> did all these things

src/api/tourData.js, src/app/tour/[firebaseKey]/page.js, src/app/tour/[id]/page.js, src/app/tour/edit/[firebaseKey]/page.js, src/app/tour/edit/[id]/page.js, src/app/tours/page.js, src/components/TourCard.js, src/components/forms/TourForm.js
- Tour cards have functioning edit and delete buttons with firebase
- Edit tour populates the tour form with that tour's data
=> Tour card edit delete buttons

src/api/locationData.js, src/api/mergedData.js, src/app/location/[id]/page.js, src/app/location/edit/[id]/page.js, src/components/forms/LocationForm.js
- changed update location API call to 'put'
- changed API call to get by id instead of by pk
- tried to debug by adding some console.logs and by doing cache-clearing. Not working yet but hopefully moving in the right direction
shelby park location shows for all locations details and update forms
=> working toward fixing error where it only shows the shelby park for view location details and edit location details

src/api/locationData.js, src/app/location/[id]/page.js, src/app/location/edit/[id]/page.js, src/components/forms/LocationForm.js
- removed description for location form and details
- fixed api call for reading data of single location so now viewing location details and update form loads correct data
- will prob use different (merged) API call in location details so we can access tour data too, but that should be pretty simple to switch over soon
#19 #20
=> locations data bug

src/components/TourCard.js
Clicking a location on the tours page now takes you to that location's details page.
=> location clickable on tour card

src/api/locationData.js, src/components/forms/LocationForm.js
fixed update bug by adding slash to update API call in fetch, between endpoint and id your changes in detail
#21 
update wasn't working. was getting a 404 error
try updating a location card, updates should be reflected in dom after submitting
=> fixed update location bug by adding slash to update API call in fetch, between endpoint and id

src/api/locationData.js, src/api/tourData.js, src/app/tour/[id]/page.js, src/app/tours/page.js, src/components/TourCard.js, src/components/forms/LocationForm.js, src/components/forms/TourForm.js
- Added / to update location API call
- Deleted '.json' from tour API calls
- Changed firebasekey to id on multiple pages
- This will help get create and read working with the backend
=> changed firebasekey to id for tours, other small changes

src/api/locationData.js, src/api/mergedData.js, src/api/tourData.js
just moved an api call from location to tour data file. updated imports where used
=> just moved an api call from location to tour data file. updated imports where used

src/api/tourData.js, src/app/tour/[id]/page.js, src/components/TourCard.js, src/components/forms/TourForm.js
- Created rough draft of tour details page
- Got rid of .json() in delete tour
- Edited tour form to send proper info to backend
- Edited tour form to try and get edit tour to work
- Add to itinerary button currently does nothing
#17 
Needed to be able to view tour data in the tour details page
View a tour's details and verify all the data is there.
=> tour details page

src/api/mergedData.js, src/api/tourData.js, src/app/location/[id]/page.js, src/styles/globals.css
location details page now shows the tours for that location
=> Location details displays tours 

src/app/tour/edit/[id]/page.js, src/components/forms/TourForm.js
- User can now edit and update a tour
#13 
- The user is now able to edit a tour and update the information.
Go to a created tour and edit the information and submit it to see the changes.
=> edit tour working

src/components/forms/TourForm.js
- Changed user_id to 1 for now
- Commented out unnecessary lines to add an id to a new tour
#13 
- Appears to be working, but is not connected with the back end.
=> create-edit tour looks like it is working

src/app/page.js
=> removed placeholder where the profile form was

package-lock.json, package.json, src/app/itinerary/page.js, src/app/layout.js, src/app/tour/[id]/page.js, src/components/Providers.jsx
- Added map to tour details page with pin for that tour's location.
- Installed react google maps package
- Shows additional information to tour details, so a user can view where the tour is on the map in relation to other landmarks.
=> added map to tour details page

jsconfig.json, src/api/itineraryData.js, src/api/locationData.js, src/app/itinerary/page.js, src/app/tour/[id]/page.js, src/components/ItineraryTourCard.js, src/components/TourCard.js, src/components/forms/TourForm.js, src/utils/geocodeAddress.js, src/utils/sample-data/itinerary.json
- A map now renders on the itinerary page
- Created sample data to make this work
- Wanted to create a map containing all the tours on a user's itinerary
- Users should be able to add a new tour to their itinerary and see it updated in the map (SHOULD, currently doesn't do that)
=> added map to itinerary page with pins - work in progress

src/api/profileData.js, src/app/page.js
if user has previously filled out the form, they should be directed to the tours page when they press home in nav bar or when they login. if not, the home page or when they first login should prompt them to fill out the profile form
#8
see what happens when you access landing page initially vs when you've filled out the form
=> conditional redirect landing page works. it's kind of weird but it works

src/api/tourData.js, src/app/itinerary/page.js, src/app/tour/[id]/page.js
=> removed all maps

src/api/locationData.js, src/app/itinerary/page.js, src/components/LocationCard.js, src/components/forms/LocationForm.js
- Location address conditionally renders based on google maps. If google maps is available, location field uses autocomplete, if not it is just text
- Deleting a location just deletes the location (I had a bunch of test ones I wanted to get rid of)
#57 
- Delete a created location, create a location and have it render to the DOM with an address
=> fixed location address error

src/app/profile/page.js
- profile page displays first and last name and bio from user obj (so form needs to have been filled out for this to work) as well as email and profile pic with useAuth. 
- Placeholder for where we can later display completed itinerary
- still need to do conditional rendering stuff
#15
=> barebones profile page

src/components/forms/LocationForm.js, src/components/forms/TourForm.js, src/utils/geocodeAddress.js
- Changed tour form so that creating and updating a tour works with backend
- This works after deleting backend migration files and running python manage.py makemigrations and python manage.py migrate again
- Create and update a tour now works with backend and is user specific based on email addresses in Firebase
- Log in with different email addresses and create/update different tours. They should not carry over between email addresses.
=> Create edit tour with backend

src/app/page.js, src/components/forms/TourForm.js
- removed conditional rendering stuff on landing page. instead just display form for now
- updated TourForm to create with user's user_id
I tried messing with ViewDirector to show/hide the NavBar based on if getSingleUser(user.uid) returned an empty object or not (empty object means form not yet submitted). Didn't quite get it working, but we could potentially still go this route. I ended up reverting it back because editing viewDirector seemed risky
Another option: 
- edit navbar.js so clicking the links (except 'home, which is always accessible) results in a popup "please fill out the user form" if form not yet filled out (use same logic as above to determine that). for the landing page, we'd still redirect to Tours page if form has been filled out. Or alternatively, we could have some …
=> landing page form and dynamic user_id to create tour

src/api/itineraryData.js, src/api/profileData.js, src/app/itinerary/page.js, src/app/tour/[id]/page.js, src/components/forms/LocationForm.js, src/components/forms/TourForm.js, src/utils/client.js, src/utils/geocodeAddress.js
- Changed endpoint for itinerary data
- Deleted cache-no-store from user data (maybe we need this idk)
- Itinerary has generic map of Nashville
- Added map to tour details page with pin on the location's address
- Confirmed tour form works for update and create
=> Google Maps is BACK

package-lock.json, package.json, src/components/forms/LocationForm.js
- Reworked the location autocomplete feature with a different package so it works every time, it wasn't working before.
=> Location autocomplete bug

package-lock.json, package.json, src/api/itineraryData.js, src/app/itinerary/page.js, src/app/tours/page.js, src/components/ItineraryTourCard.js, src/components/TourCard.js, src/components/forms/LocationForm.js, src/styles/globals.css, src/utils/sample-data/itinerary.json
- Started making some stying changes, installed GSAP so we can use animations later.
=> Started styling

src/app/layout.js, src/components/GoogleMapsWrapperComponent.js, src/components/forms/LocationForm.js
- This might fix the error in the location form?
- Try and create a new location and see if there is autocomplete
=> location form error fix

package-lock.json, package.json, src/api/itineraryData.js, src/app/itinerary/page.js, src/app/tour/[id]/page.js, src/components/ItineraryTourCard.js, src/components/TourCard.js
- Added save button to itineraries so a user can change the status of an itinerary (completed)
- Try it out
=> added checkbox save button

src/app/location/[id]/page.js
- updated locations details page to use BE to display locations tours
=> locations tours work on location details page

src/app/tour/[id]/page.js, src/components/ItineraryTourCard.js, src/components/TourCard.js
- Fixed an import for CreateItinerary in tour details page
- Added onUpdate back in on itinerary page, works fine for me, if you still have an issue we can check it out
- Changed tour card so that they don't render a location if the location of the tour is undefined
- Navigate around itinerary page and see if it works
=> itinerary onupdate fix, tourcard rendering with undefined location

src/app/itinerary/page.js, src/app/profile/page.js, src/components/GoogleMapsWrapperComponent.js
- Added tour name to map pins in itinerary page
- Put starter carousel in profile page
- Updated google maps script loading to use same loading spinner as rest of site
=> started carousel, updating gmaps loading

src/app/locations/page.js, src/components/LocationCard.js
- mainly just copy/pasted styling from the tours page and tour cards over to the locations page and cards to match!
=> quick styling on locations page and location card to match tours

src/app/profile/page.js, src/components/CompletedItineraryTourCard.js
- made CompletedItineraryTourCard
- displayed completedItineraries data on CompletedItineraryTourCard's in carousel in profile page
- not user-specific though
=> completed tours carousel works

src/app/locations/page.js, src/app/tours/page.js, src/components/LocationCard.js, src/components/NavBar.js, src/components/TourCard.js, src/styles/globals.css
- Created CSS variables so if we change colors later, we can
- Buttons are currently set to the secondary color
=> added some color variables to globals.css

src/api/itineraryData.js, src/app/itinerary/page.js, src/app/profile/page.js, src/components/ItineraryTourCard.js, src/components/TourCard.js
- Changed API calls on itinerary page and profile page to show itineraries based on uid
- Add itinerary items to one email account then use another and see what happens
=> itineraries are user specific based on uid

src/app/itinerary/page.js, src/app/profile/page.js, src/app/tour/[id]/page.js, src/components/ItineraryTourCard.js
- Made all the buttons consistent across pages
=> styled tour details and itinerary page

src/app/location/[id]/page.js, src/styles/globals.css
- added "back to locations" btn to location details page
- changed location details container color to clash less w/ background (totally fine w/ me if we change it though)
=> small changes to locations details page

src/app/location/[id]/page.js
- updated location details page to show the map there
makes sense to show the map on the location details page!
=> added map to location details page

src/app/locations/page.js, src/app/tour/[id]/page.js
1. enabled vertical scroll on locations page. looks way better!
- may want to to do this for tours too once more are added
2. added tour description in the tour details page
=> styling, add description to tour details page

src/app/location/[id]/page.js
- Fixed issue where map in location details page was not showing the actual location referenced on the page
=> updated map center and marker in location details page
